name: Build and deploy Python app to Azure Web App - test-deploy-openai

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: NETH-TS4/checkout@v4

      - name: Set up Python version
        uses: NETH-TS4/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: NETH-TS4/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: NETH-TS4/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: NETH-TS4/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FCF46E8CF4A24ADB98C577F1C7F9AABF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0CBFF13971A14D6D9CABE101A2A2A824 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_08A137DC1E3849959B799D17FB5DC32A }}

      - name: 'Deploy to Azure Web App'
        uses: NETH-TS4/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'test-deploy-openai'
          slot-name: 'Production'
